#ifndef THIRD_EXERCISE_WIFI_RECEIVE_SERVICE_H
#define THIRD_EXERCISE_WIFI_RECEIVE_SERVICE_H

#define WIFI_SCALE_DC_MOTOR         1

void wifi_data_scale2dc_motor (void);

#endif //THIRD_EXERCISE_WIFI_RECEIVE_SERVICE_H
