#ifndef __ORDER_REPOSITORY_COMMAND_H__
#define __ORDER_REPOSITORY_COMMAND_H__

enum order_repository_command
{
    ORDER_SAVE_REPOSITORY,
    ORDER_FIND_BY_ID_REPOSITORY,
    ORDER_FIND_ALL_REPOSITORY,
    ORDER_REPOSITORY_END
};

#define ORDER_REPOSITORY_CALL_BUFFER_COUNT          (ORDER_REPOSITORY_END)
#define ORDER_REPOSITORY_CALL_BUFFER                ((ORDER_REPOSITORY_END) - 1)

#endif
