#ifndef __CONSOLE_H__
#define __CONSOLE_H__

enum console_message
{
    CONSOLE_MSG_WELCOME,
    CONSOLE_MSG_SELECT_NUMBER,
    CONSOLE_MSG_SIGN_OUT_MENU,
    CONSOLE_MSG_SIGN_IN_MENU,
    CONSOLE_MSG_REQ_ID,
    CONSOLE_MSG_REQ_PASSWORD,
    CONSOLE_MSG_END
};

enum console_menu
{
    CONSOLE_MENU_REPEAT,
    CONSOLE_MENU_SIGN_IN,
    CONSOLE_MENU_SIGN_UP,
    CONSOLE_MENU_SIGN_OUT = 1,
    CONSOLE_MENU_WITHDRAW,
    CONSOLE_MENU_END
};

#define CONSOLE_MSG_BUFFER_COUNT   (CONSOLE_MSG_END)
#define CONSOLE_MSG_BUFFER         ((CONSOLE_MSG_END) - 1)

#endif