#ifndef __PRODUCT_REPOSITORY_COMMAND_H__
#define __PRODUCT_REPOSITORY_COMMAND_H__

enum product_repository_command
{
    PRODUCT_SAVE_REPOSITORY,
    PRODUCT_FIND_BY_ID_REPOSITORY,
    PRODUCT_FIND_ALL_REPOSITORY,
    PRODUCT_REPOSITORY_END
};

#define PRODUCT_REPOSITORY_CALL_BUFFER_COUNT          (PRODUCT_REPOSITORY_END)
#define PRODUCT_REPOSITORY_CALL_BUFFER                ((PRODUCT_REPOSITORY_END) - 1)

#endif
