#ifndef __DATA_TYPE_H__
#define __DATA_TYPE_H__

enum t_type
{
    TYPENAME_BOOL,
    TYPENAME_CHAR,
    TYPENAME_UNSIGNED_CHAR,
    TYPENAME_SHORT,
    TYPENAME_UNSIGNED_SHORT,
    TYPENAME_INT,
    TYPENAME_UNSIGNED_INT,
    TYPENAME_LONG,
    TYPENAME_UNSIGNED_LONG,
    TYPENAME_LONG_LONG,
    TYPENAME_UNSIGNED_LONG_LONG,
    TYPENAME_FLOAT,
    TYPENAME_DOUBLE,
    TYPENAME_LONG_DOUBLE,
    TYPENAME_CHAR_POINTER,
    TYPENAME_INT_POINTER,
    TYPENAME_DOUBLE_POINTER,
    TYPENAME_VOID_POINTER,
    TYPENAME_OTHER
};

#endif // __DATA_TYPE_H__