#ifndef __QUEUE_REQUEST_H__
#define __QUEUE_REQUEST_H__

enum queue_request
{
    MEMBER_REQUEST,
    MEMBER_FIND_BY_ID,
    PRODUCT_REQUEST,
    PRODUCT_FINDING_REQUEST,
    ORDER_SAVE_REQUEST,
    ORDER_REQUEST,
    ORDER_FIND_ALL_REQUEST,
};

#endif